<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vm</string>
	</array>
	<key>name</key>
	<string>Velocity</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>things like $var.function</string>
			<key>match</key>
			<string>\.([a-zA-Z]+)</string>
			<key>name</key>
			<string>entity.name.function.velocity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$\!?\{?[[a-zA-Z]a-zA-Z0-9_]+(\}|\b)</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\*</string>
			<key>end</key>
			<string>\*\#</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\*\*</string>
			<key>end</key>
			<string>\*\#</string>
			<key>name</key>
			<string>comment.block.documentation</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|in|foreach|return|ifelse|else|elseif|case|macro|end|stop|set)\b</string>
			<key>name</key>
			<string>keyword.control.velocity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.velocity</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.velocity</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.velocity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\$\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>source.velocity.embedded.source</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>!|\$|%|&amp;|\*|\-\-|\-|\+\+|\+|~|===|==|=|!=|!==|&lt;=|&gt;=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|&lt;&gt;|&lt;|&gt;|!|&amp;&amp;|\|\||\?\:|\*=|(?&lt;!\()/=|%=|\+=|\-=|&amp;=|\^=|\b(in|instanceof|new|delete|typeof|void)\b</string>
			<key>name</key>
			<string>keyword.operator.velocity</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(TRUE|FALSE|NULL|__(FILE|FUNCTION|CLASS|METHOD|LINE)__|ON|OFF|YES|NO|NL|BR|TAB)\b</string>
			<key>name</key>
			<string>constant.language.velocity</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.velocity</string>
	<key>uuid</key>
	<string>cafc6d57-118b-466e-b1a3-5b3ec2100377</string>
</dict>
</plist>
